version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - DB_FILE=sqlite:///./data.sqlite
      - JWT_SECRET=replace_with_a_strong_secret
      - JWT_EXPIRES_SECONDS=7200
